/**
 * Architecture Target: sqlite-web-api
 *
 * A lightweight REST API backed by SQLite.
 * Stack: Hono (HTTP) + better-sqlite3 (DB) + Zod (validation)
 */

import type { Architecture } from '../models/architecture.js';

// ─── Shared files (written once, not generated by LLM) ─────────────────────

const DB_FILE = `import Database from 'better-sqlite3';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const DB_PATH = process.env.DB_PATH ?? 'data/app.db';

// Ensure directory exists
const dir = dirname(DB_PATH);
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

const db = new Database(DB_PATH);

// Enable WAL mode for better concurrent read performance
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

/**
 * Run migrations. Each migration is idempotent (CREATE TABLE IF NOT EXISTS).
 * Modules register their migrations at import time.
 */
const migrations: Array<{ name: string; sql: string }> = [];

export function registerMigration(name: string, sql: string): void {
  migrations.push({ name, sql });
}

export function runMigrations(): void {
  for (const m of migrations) {
    db.exec(m.sql);
  }
}

export { db };
export type { Database };
`;

const APP_FILE = `import { Hono } from 'hono';
import { logger } from 'hono/logger';
import { cors } from 'hono/cors';

const app = new Hono();

app.use('*', logger());
app.use('*', cors());

app.get('/health', (c) => c.json({ status: 'ok', uptime: process.uptime() }));

/**
 * Mount a route module. Call this for each generated module.
 */
export function mount(path: string, router: Hono): void {
  app.route(path, router);
}

export { app };
`;

const SERVER_FILE = `import { serve } from '@hono/node-server';
import { app } from './app.js';
import { runMigrations } from './db.js';

// Import generated route modules (populated by scaffold)
// __ROUTE_IMPORTS__

const port = parseInt(process.env.PORT ?? '3000', 10);

// Run database migrations before starting
runMigrations();

console.log(\`Server running at http://localhost:\${port}\`);
serve({ fetch: app.fetch, port });
`;

// ─── LLM prompt extension ───────────────────────────────────────────────────

const SYSTEM_PROMPT_EXTENSION = `
## Architecture: sqlite-web-api

You are generating a route handler module for a Hono REST API backed by SQLite.

### CRITICAL import rules — follow EXACTLY
- Import \`{ Hono }\` from 'hono'
- Import \`{ db, registerMigration }\` from '../../db.js' — the shared database module is TWO levels up from the generated module.
- Import \`{ z }\` from 'zod'
- NEVER create your own Database instance. NEVER write \`new Database(...)\` or \`import Database from 'better-sqlite3'\`. The shared db.js provides the single db connection.
- NEVER define your own Hono class or Database type. Import them from the packages.

### Module structure
- Export a Hono router instance as the DEFAULT export: \`export default router;\`
- Register your table schema via \`registerMigration('tablename', 'CREATE TABLE IF NOT EXISTS ...')\` at module scope.
- Include ALL CRUD routes for the resource in a single module (GET list, GET by id, POST create, PATCH update, DELETE).
- Use better-sqlite3 synchronous API: db.prepare(sql).run(), .get(), .all()
- Use parameterized queries ALWAYS — never interpolate user input into SQL.
- Parse request bodies with \`await c.req.json()\` and validate with Zod .safeParse().

### Response conventions
- 200 for successful reads
- 201 for successful creates (return the created resource)
- 204 for successful deletes (return c.body(null, 204))
- 400 for validation errors: \`{ error: "message" }\`
- 404 for not found: \`{ error: "Not found" }\`

### Data model
- Use integer primary keys with AUTOINCREMENT.
- Include a \`completed\` boolean column (as INTEGER 0/1) for task/todo resources when the spec mentions it.
- Include \`created_at TEXT NOT NULL DEFAULT (datetime('now'))\` for timestamps.
`;

const CODE_EXAMPLES = `
## Architecture Pattern Examples

### Example 1: CRUD route module for a "notes" resource

\`\`\`typescript
import { Hono } from 'hono';
import { z } from 'zod';
import { db, registerMigration } from '../../db.js';

// Register table migration
registerMigration('notes', \`
  CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )
\`);

const CreateNoteSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().optional().default(''),
});

const UpdateNoteSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  body: z.string().optional(),
});

const router = new Hono();

// List all notes
router.get('/', (c) => {
  const notes = db.prepare('SELECT * FROM notes ORDER BY created_at DESC').all();
  return c.json(notes);
});

// Get single note
router.get('/:id', (c) => {
  const note = db.prepare('SELECT * FROM notes WHERE id = ?').get(c.req.param('id'));
  if (!note) return c.json({ error: 'Note not found' }, 404);
  return c.json(note);
});

// Create note
router.post('/', async (c) => {
  const result = CreateNoteSchema.safeParse(await c.req.json());
  if (!result.success) return c.json({ error: result.error.issues[0].message }, 400);
  const { title, body } = result.data;
  const info = db.prepare('INSERT INTO notes (title, body) VALUES (?, ?)').run(title, body);
  const note = db.prepare('SELECT * FROM notes WHERE id = ?').get(info.lastInsertRowid);
  return c.json(note, 201);
});

// Update note
router.patch('/:id', async (c) => {
  const id = c.req.param('id');
  const existing = db.prepare('SELECT * FROM notes WHERE id = ?').get(id);
  if (!existing) return c.json({ error: 'Note not found' }, 404);
  const result = UpdateNoteSchema.safeParse(await c.req.json());
  if (!result.success) return c.json({ error: result.error.issues[0].message }, 400);
  const updates = result.data;
  if (updates.title !== undefined) db.prepare('UPDATE notes SET title = ? WHERE id = ?').run(updates.title, id);
  if (updates.body !== undefined) db.prepare('UPDATE notes SET body = ? WHERE id = ?').run(updates.body, id);
  const updated = db.prepare('SELECT * FROM notes WHERE id = ?').get(id);
  return c.json(updated);
});

// Delete note
router.delete('/:id', (c) => {
  const id = c.req.param('id');
  const existing = db.prepare('SELECT * FROM notes WHERE id = ?').get(id);
  if (!existing) return c.json({ error: 'Note not found' }, 404);
  db.prepare('DELETE FROM notes WHERE id = ?').run(id);
  return c.body(null, 204);
});

export default router;

export const _phoenix = {
  iu_id: 'example',
  name: 'Notes',
  risk_tier: 'medium',
  canon_ids: [],
} as const;
\`\`\`

### Key patterns to follow:
1. registerMigration() at module scope — idempotent CREATE TABLE IF NOT EXISTS
2. Zod schemas for create/update request validation
3. .safeParse() + early return with 400 on failure
4. Parameterized SQL queries (? placeholders)
5. Return the created/updated resource after mutation
6. 404 checks before update/delete
7. Export default router + export _phoenix metadata
`;

// ─── Architecture definition ────────────────────────────────────────────────

export const sqliteWebApi: Architecture = {
  name: 'sqlite-web-api',
  description: 'REST API backed by SQLite — Hono + better-sqlite3 + Zod',
  runtime: 'node',

  packages: {
    'hono': '^4.6.0',
    '@hono/node-server': '^1.13.0',
    'better-sqlite3': '^11.7.0',
    'zod': '^3.24.0',
  },

  devPackages: {
    'typescript': '^5.4.0',
    'vitest': '^2.0.0',
    '@types/node': '^22.0.0',
    '@types/better-sqlite3': '^7.6.0',
    'tsx': '^4.0.0',
  },

  systemPromptExtension: SYSTEM_PROMPT_EXTENSION,
  codeExamples: CODE_EXAMPLES,

  sharedFiles: {
    'src/db.ts': DB_FILE,
    'src/app.ts': APP_FILE,
  },

  packageJsonExtras: {
    scripts: {
      dev: 'tsx watch src/server.ts',
      start: 'tsx src/server.ts',
      build: 'tsc',
      test: 'vitest run',
    },
  },
};
